package-lock.json
src/components/Layout.tsx
src/pages/_app.tsx
src/pages/index.tsx
tailwind.config.js

style: 공통 레이아웃 작업 진행

---

package-lock.json
package.json
src/components/buider/EditSiteInfo/index.tsx
src/components/buider/MainColor/index.tsx
src/components/buider/TopBar/index.tsx
src/pages/builder/index.tsx
src/types/builder.ts
tailwind.config.js

#11 
- `/builder` 페이지에서 작업한 내용 확인할 수 있습니다. 진행 사항은 Builder top bar의 메인컬러 부분입니다.

패키지 설치 및 빌더 상단바 영역의 메인컬러 기능 구현

---

next.config.js
src/apis/auth.ts
src/apis/axios.ts
src/components/input.tsx
src/interfaces/auth.ts
src/middleware.ts
src/pages/_app.tsx
src/pages/login/index.tsx
src/utiles/bearerToken.ts
yarn.lock

login 기능 개발

---

src/components/button.tsx
src/components/input.tsx
src/pages/index.tsx
src/pages/login/index.tsx
src/pages/register/index.tsx
yarn.lock

login 디자인 수정

---

src/apis/auth.ts
src/apis/axios.ts
src/components/button.tsx
src/components/input.tsx
src/interfaces/auth.ts
src/pages/findid/index.tsx
src/pages/findpass/index.tsx
src/pages/login/index.tsx
src/pages/register/index.tsx
src/pages/repass/index.tsx
src/pages/snsregister/index.tsx

#1 
- react-hook-form의 특성을 이해
- 아이디 찾기 ui
- 비밀번호 찾기 ui
- 비밀번호 재설정 ui
- button, input 리펙토링 진행
- 주의 사항

아이디찾기 , 비빌번호 찾기 , 비밀번호 재설정 ui , button 리펙토링

---

src/apis/auth.ts
src/apis/axios.ts
src/components/input.tsx
src/interfaces/auth.ts
src/pages/findid/index.tsx
src/pages/findpass/index.tsx
src/pages/repass/index.tsx

아이디 찾기 , 비밀번호 찾기, 비밀번호 재설정 기능 구현

---

src/components/Layout.tsx
src/styles/globals.css

feat: 폰트 추가 및 기본 폰트 설정하기

---

src/components/buider/Layout/index.tsx

Builder 공통 컴포넌트 파일 및 폴더 이름 변경

---

.prettierrc

- .prettierrc 파일 이름에서 띄어쓰기를 잘못한 것을 확인했습니다... 다시 이름을 수정했지만 아마 수정된 환경에 맞춰서 변경될 것 같습니다. 정말 죄송합니다.

.prettierrc 파일 수정

---

src/components/builder/Menu/index.tsx
src/store/index.tsx

위젯 목록에서 헤더/푸더 부분 제거

---

src/components/builder/Layout/index.tsx
src/components/builder/LeftPanel/index.tsx
src/components/builder/MainColor/index.tsx
src/components/common/button/index.tsx
src/components/common/input/index.tsx
src/interfaces/button.ts
src/interfaces/input.ts
src/pages/builder/changeCompany.tsx
src/pages/builder/changeSite.tsx
src/pages/builder/index.tsx

#66 
- coponents/common/input/index.tsx 파일 참고
- onChange 함수와 setValue 함수가 존재하는데, 존재하는 Props 값 참고

빌더 공통 컴포넌트 작업 진행

---

src/components/builder/Preview/index.tsx
src/components/builder/Widget/index.tsx
src/components/common/toggle/index.tsx
src/interfaces/toggle.ts
src/pages/builder/headerfooter.tsx
src/pages/builder/keyvisual.tsx
src/styles/globals.css

#66 #60 #65 #32 
- ToggleWidget 컴포넌트 Props 값 변경으로 인해 만일 해당 컴포넌트 사용 시 수정해야 할 수 있습니다.
- 글로벌 폰트 이름을 변경했기 때문에 해당 폰트를 사용중이라면 수정하셔야 합니다.

헤더/푸터 미리보기 위젯 컴포넌트 구현 및 - ToggleWidget 컴포넌트 Props 값 변경

---

src/apis/auth.ts
src/components/builder/Widget/index.tsx
src/components/common/input/index.tsx
src/components/common/product/index.tsx
src/interfaces/auth.ts
src/interfaces/button.ts
src/interfaces/input.ts
src/interfaces/store.ts
src/pages/builder/productservice.tsx
src/pages/index.tsx
src/pages/mypage/index.tsx
src/pages/register/index.tsx
src/store/index.tsx
src/utils/fileCheck.ts

제품/서비스 소개 기능

---

src/apis/axios.ts
src/apis/builder.ts
src/components/builder/MainColor/index.tsx
src/components/common/input/index.tsx
src/hooks/useBuilder.ts
src/hooks/useUpdateCompany.ts
src/hooks/useUploadImage.ts
src/hooks/useUploadSite.ts
src/interfaces/input.ts
src/interfaces/store.ts
src/pages/builder/changeCompany.tsx
src/pages/builder/changeSite.tsx
src/pages/builder/changeTheme.tsx
src/pages/builder/index.tsx
src/store/index.tsx
src/utils/fileCheck.ts
yarn.lock

#42 #45 #47 
- axios를 변경해서 axiosInstance 사용 시 기존에 작성한 axiosInstance에서 axiosInstance()로 변경해야 함.

테마 변경 & 회사 정보 수정 & 사이트 정보 수정 페이지 초기값 설정 및 API 데이터 전송

---

package-lock.json
package.json
src/apis/auth.ts
src/apis/dashborad.ts
src/components/common/button/index.tsx
src/components/common/popup/index.tsx
src/components/dashboard/Loader.tsx
src/components/dashboard/contact/InquiryTable.tsx
src/components/dashboard/main/Count.tsx
src/components/dashboard/main/DashboardContents.tsx
src/components/dashboard/main/LandingPage.tsx
src/components/dashboard/main/TodayCounts.tsx
src/components/dashboard/main/WeeklyCounts.tsx
src/hooks/useDashboard.ts
src/interfaces/dashboard.ts
src/interfaces/popup.ts
src/pages/dashboard/main/index.tsx
src/styles/globals.css
yarn.lock

#92 
1.
2.
- `date-fns` 설치하여 사용했습니다.
- test7번 아이디에 서버에서 다운로드 횟수 제외하고 다른 값들 임의로 넣어주었습니다.

대시보드 > 메인 메뉴 #92

---

package-lock.json
src/apis/auth.ts
src/components/builder/Widget/index.tsx
src/components/common/button/index.tsx
src/components/common/product/index.tsx
src/components/input.tsx
src/hooks/useVerify.ts
src/interfaces/auth.ts
src/interfaces/store.ts
src/middleware.ts
src/pages/_app.tsx
src/pages/builder/history.tsx
src/pages/builder/index.tsx
src/pages/builder/press.tsx
src/pages/builder/productservice.tsx
src/pages/builder/teammember.tsx
src/pages/findid/index.tsx
src/pages/findpass/index.tsx
src/pages/login/index.tsx
src/pages/mypage/index.tsx
src/pages/register/index.tsx
src/store/index.tsx
src/utils/fileCheck.ts
yarn.lock

로그인/회원가입 placeholder추가, user 인증 검사, Protected Router 구현, 연혁 추가/삭제 기능, 팀 멤버 추가/삭제 기능, 제품/서비스 기능 수정

---

src/apis/subdomain.ts
src/components/builder/Preview/index.tsx
src/components/builder/Widget/index.tsx
src/components/subdomain/Widget.tsx
src/interfaces/subdoamin.ts
src/pages/builder/index.tsx
src/pages/subdomain/[id].tsx

미리보기 컴포넌트 디자인 수정 및 회사 소개 페이지 제작 진행

---

src/pages/builder/index.tsx

widget_name에서 widget_id 값으로 변경

---

src/apis/dashborad.ts
src/components/subdomain/Widget.tsx
src/data/channel.ts
src/interfaces/subdoamin.ts
src/pages/subdomain/[id].tsx

회사 소개 페이지 키비주얼 & 미션비전 & 해더푸터 & 다운로드 & 채널 디자인 완료

---

src/components/dashboard/side/CompanyPreview.tsx
src/components/subdomain/Widget.tsx
src/pages/dashboard/contact/index.tsx

회사 소개 페이지 디자인 수정

---

src/middleware.ts

미들웨어 주소 수정 테스트

---

src/hooks/useVerify.ts
src/middleware.ts

#1 
- 로그인 전에 유저가 회원가입/아이디찾기/비밀번호 찾기 접속 가능하게 수정
- 그전에는 login페이지로 넘어감
- 주의 사항

로그인 전에 유저가 회원가입/아이디찾기/비밀번호 찾기 접속 가능하게 수정

---

src/apis/auth.ts
src/components/common/Header.tsx
src/components/common/icons/ExclamationTriangle.tsx
src/components/dashboard/DropdownExcel.tsx
src/components/dashboard/side/CompanyPreview.tsx

fix: 빌드 에러 해결
